apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: mariadb
  name: mariadb
spec:
  ports:
    - name: "mariadb"
      port: 3306
      targetPort: 3306
  selector:
    service.name: mariadb
