apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      service.name: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service.name: nextcloud
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: MYSQL_PASSWORD
              value: "<MYSQL_ROOT_PASSWORD>"
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: root
            - name: MYSQL_HOST
              value: "mariadb:3306"
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "<NEXTCLOUD_ADMIN_PASSWORD>"
            - name: NEXTCLOUD_DATA_DIR
              value: /data
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "*.ngrok.io"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_HOST_PORT
              value: "6379"
          image: nextcloud
          name: nextcloud
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/ 
              name: nextcloud-config
            - mountPath: /data
              name: nextcloud-data
      restartPolicy: Always
      volumes:
        - name: nextcloud-config
          hostPath:
            path: /apps/docker/nextcloud/app
            type: DirectoryOrCreate
        - name: nextcloud-data
          hostPath:
            path: /apps/docker/nextcloud/data
            type: DirectoryOrCreate
