apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: nextcloud
  name: nextcloud
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    service.name: nextcloud
